# Generated by Django 5.0.14 on 2025-12-21 14:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(blank=True, max_length=50, null=True)),
                ('shipping_address_json', models.JSONField(default=dict, help_text='Stores street, city, zip, messages, gps')),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(choices=[('En attente', 'En attente'), ('En préparation', 'En préparation'), ('Livré', 'Livré'), ('Annulé', 'Annulé')], default='En attente', max_length=50)),
                ('payment_method', models.CharField(choices=[('Carte Bancaire', 'Carte Bancaire'), ('Espèces à la livraison', 'Espèces à la livraison'), ('Espèces (POS)', 'Espèces (POS)'), ('Payer en ligne', 'Payer en ligne'), ('Payer à la livraison', 'Payer à la livraison')], default='Payer en ligne', max_length=50)),
                ('payment_status', models.CharField(choices=[('Payé', 'Payé'), ('En attente', 'En attente'), ('Remboursé', 'Remboursé')], default='En attente', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=255)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='orders.order')),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.product')),
            ],
        ),
    ]
