# Generated by Django 5.0.14 on 2025-12-24 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_alter_order_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='is_viewed',
            field=models.BooleanField(default=False),
        ),
    ]
