# Generated by Django 5.0.14 on 2025-12-26 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_order_is_viewed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('En attente', 'En attente'), ('En préparation', 'En préparation'), ('Livré', 'Livré'), ('Annulé', 'Annulé')], db_index=True, default='En attente', max_length=50),
        ),
    ]
