# Generated by Django 5.0.14 on 2025-12-21 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DeliveryZone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Nom de la zone (ex: Centre-ville, Calavi, etc.)', max_length=100)),
                ('city', models.CharField(default='Cotonou', max_length=100)),
                ('price', models.PositiveIntegerField(help_text='Prix de la livraison en FCFA')),
                ('estimated_time', models.CharField(blank=True, help_text='Temps estimé (ex: 20-30 min)', max_length=50, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['city', 'price'],
            },
        ),
    ]
